spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bobbti.cemcoksbd5o4.ap-northeast-2.rds.amazonaws.com:3306/bobbti
    username: root
    password: rkskekfk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect